kind: pipeline
type: docker
name: default
steps:
  - name: build_test_image
    image: docker:latest
    volumes: 
      - name: docker_socket
        path: /var/run/docker.sock
    commands:
      - docker build -t local-pytest:test -f Dockerfile .

  - name: run_test_suite
    image: local-pytest:test
    pull: never
    commands:
      - pytest -vv
    depends_on:
      - build_test_image

        #volumes:
        #  - name: docker_socket
        #    host:
        #      path: /var/run/docker.sock
